- name: create ec2 instance and route53 records
  hosts: localhost
  vars:
    zone: "surya-devops.site"
    instances:
    - db
    - backend
    - frontend
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        instance_type: t2.micro
        name: "{{item}}"
        security_group: test-sg
        image_id: ami-0220d79f3f480ecf5
        tags:
          Name: "{{item}}"
      loop:
      - db
      - backend
      - frontend
      register: ec2_instance_info

    - name: print register output
      ansible.builtin.debug:
        msg: "Output:: {{ec2_instance_info}}"

    - name: create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{zone}}"
        record: "{{item}}.{{zone}}"
        value: "{{item.private_ip_address}}"
        type: A
        ttl: 1
        overwrite: true
        loop: "{{ c2_instance_info.results.instances }}"





